package_imports:
  - fmt
  - errors
  - math

package: vehicle

custom_structs:
  - name: Car
    fields:
      - name: doors
        type: int
      - name: insured
        type: bool

  - name: VehicleStatus
    fields:
      - name: Speed
        type: int
      - name: Direction
        type: string
      - name: EngineOn
        type: bool

  - name: VehicleStatus2
    fields:
      - name: Speed
        type: int
      - name: Direction
        type: string
      - name: EngineOn
        type: bool
# Moved interface details to the root level
name: Vehicle
concrete: Car
methods:
  - name: GetTopSpeed
    inputs: []
    outputs:
      - type: int

  - name: Turn
    inputs:
      - name: dir
        type: string
    outputs:
      - name: newDir
        type: string

  - name: Reverse
    inputs: []
    outputs:
      - type: string
      - type: error

  - name: Accelerate
    inputs:
      - name: speed
        type: int
      - name: unit
        type: string
    outputs:
      - name: newSpeed
        type: int
      - name: err
        type: error

  - name: IsMoving
    inputs: []
    outputs:
      - type: bool

  - name: Honk
    inputs:
      - name: times
        type: int
    outputs: []

  - name: GetEngineSpecs
    inputs: []
    outputs:
      - name: power
        type: int
      - name: fuelType
        type: string

  - name: ApplyBrakes
    inputs:
      - name: force
        type: float64
    outputs:
      - type: bool

  - name: ChangeGears
    inputs:
      - name: gear
        type: int
    outputs:
      - name: prevGear
        type: int
      - name: newGear
        type: int

  - name: Telemetry
    inputs: []
    outputs:
      - type: "map[string]float64"

  - name: GetPassengers
    inputs: []
    outputs:
      - type: "[]string"

  - name: LoadCargo
    inputs:
      - name: items
        type: "[]string"
    outputs:
      - name: remainingCapacity
        type: int
      - name: err
        type: error

  - name: GetVehicleStatus
    inputs: []
    outputs:
      - type: VehicleStatus

  - name: UpdateStatus
    inputs:
      - name: status
        type: VehicleStatus
    outputs:
      - type: error
